### PR TITLE
Made parser constraint handling faster.

### PR DESCRIPTION
**Pull request by mhrmm**
@codeviking This change makes the parser backend considerably faster at handling constraints. Could you look it over, and if it's fine, merge and re-deploy (you'll have to ask Dirk for a new nlpstack version I suppose)? Thanks!

### CODE REVIEW

**Comment by codeviking** [comment]
:+1:

**Comment by codeviking** [comment]
@dirkgr Can you publish a new nlpstack with the latest (including this change) and let me know when it's live.

Thanks!

**Comment by dirkgr** [comment]
I just released it. It should take the usual 10 minutes or so until it’s there.

**Comment by codeviking** [comment]
Awesome -- thanks!

**Pull request merged**
