### PR TITLE
load lines into batches during parallel execution

### PR DESCRIPTION
**Pull request by afader**
The current nlpstack loads the entire input file into memory during parallel execution via a call to `toIndexedSeq`. As @dirkgr pointed out, this is kind of confusing, since you'll only want to run parallel execution on large files, which probably won't fit into memory. Here's a first attempt at a fix, following @schmmd's [famous  stackoverflow post](http://stackoverflow.com/questions/6751463/iterate-over-lines-in-a-file-in-parallel-scala).

### CODE REVIEW

**Comment by dirkgr** [comment]
LGTM!

**Comment by dirkgr** [comment]
Not that I have a better idea, but this is still a very unsatisfying solution. If there is one line in the input that takes extra long, it will hold up the whole batch, and run in a single thread until we get to the next batch. Usually, this is not as edgy a case as one would think.

**Comment by afader** [comment]
Yeah that probably happens quite a bit. Maybe there's some way to use a queue of sentences or something? Also, I don't even know if the code I wrote is correct: the processed lines could be written to the output in a different order than the input lines. Though, the existing parallel code had that same problem.

**Comment by schmmd** [comment]
They will be output in a different order.  I'd recommend making parallelization a flag.

To address the problem, I recommend making the batch size large.  10,000 or 100,000.

Alternatively you could spin up workers and round-robin or have a more complex solution to handle stragglers.

**Comment by dirkgr** [comment]
I'm pretty sure there is a general solution we could bake into the commons library. Something about queues and execution contexts. `Seq.parMap` or something. It would be very cool :-)

It's impossible to solve stragglers, in-order output, and bounded memory at the same time. If the first line takes as long as all other lines combined, and we insist on giving the output in order, we have to store all results in memory, until the first one is done.

**Comment by schmmd** [comment]
Yes, this would be a good use of time too.

`def Iterator.parForEach`

Peace.  Michael

**Comment by dirkgr** [comment]
(Just so you know, I haven't forgotten about this. I've just been busy with the keystone pipeline.)

**Comment by afader** [comment]
No prob, this is not high priority for me.

**Pull request merged**
