### PR TITLE
Weird2

### PR DESCRIPTION
**Pull request by mhrmm**
@sbhaktha Here's a PR that captures the spirit of #114 but leveraging some of the existing machinery: the Neighborhood class and the ParseStatistic class.

### CODE REVIEW

**Comment by mhrmm** [comment]
To run the training:
> tools-parse/run-main org.allenai.nlpstack.parse.poly.reranking.ParseRerankerTraining -g question-bank/stanford-patch-1.0/stan3-4-ch-dependencies/qbank.train.conllx -h question-bank/stanford-patch-1.0/stan3-4-ch-dependencies/qbank.test.conllx --datasource datastore --nbestfiles /Users/markhopkins/Projects/experiments/parsing/temp/qbank.train.50best -o /Users/markhopkins/Projects/experiments/parsing/temp/foo.rerank -v /Users/markhopkins/Projects/experiments/parsing/temp/vectors.train --clusters /Users/markhopkins/Projects/thirdparty/brown-cluster/wsj.train.arcs-c200-p1.out/paths -p /Users/markhopkins/Projects/experiments/parsing/temp/wsj64qbank.poly.json -m /Users/markhopkins/Projects/experiments/parsing/temp/qbank.test.50best

**Comment by mhrmm** [comment]
To test the trained reranker:

> tools-parse/run-main org.allenai.nlpstack.parse.poly.reranking.ParseReranker -g question-bank/stanford-patch-1.0/stan3-4-ch-dependencies/qbank.test.conllx --datasource datastore -r /Users/markhopkins/Projects/experiments/parsing/temp/foo.rerank -p /Users/markhopkins/Projects/experiments/parsing/temp/wsj128bqbank.poly.json

**Comment by mhrmm** [comment]
where you substitute in your own trained files for the local files specified.

**Comment by sbhaktha** [comment]
LGTM

**Pull request merged**
