### PR TITLE
Usefloats

### PR DESCRIPTION
**Pull request by mhrmm**
@sbhaktha This re-synchronizes the parser model with the code. There are three changes:
1. Arc labels are changed from Symbols to a ArcLabel object.
2. Floats are used instead of doubles, to save space.
3. The parser assigns arclabel and coarse POS tag when creating an edge.

### CODE REVIEW

**Comment by sbhaktha** [comment]
What are `SingleSymbolArcLabel` and `DependencyParsingArcLabel`, i.e., when is each one used? What is the `cpos` field in `DependencyParsingArcLabel` and why do we need it there? It looks like in some cases it is the `cops` of the origin node (the node the arc is originating from), for e.g., `DependencyParsingArcLabel('PREP, 'IN)`, and in some cases it is the node the arc ends at, for e.g., `DependencyParsingArcLabel('NSUBJ, 'NN)`. Some comments about them would help.

**Comment by mhrmm** [comment]
Added some comments for those classes. It is always the CPOS of the "gretel" (i.e. the non-breadcrumb) of the arc.

**Comment by sbhaktha** [comment]
LGTM

**Comment by sbhaktha** [comment]
Unable to merge -- looks like there are conflicts.

**Pull request merged**
