### PR TITLE
Justifying Classifier Outcomes

### PR DESCRIPTION
**Pull request by sbhaktha**
@mhrmm : Here it is. Pruned Random Forest justification to top (highest KL divergence) decision tree node as discussed.

Output looks like this:

```
Who was made the first honorary citizen of the U.S. ?
Good families, classified as weird:
  nexus[nexus] -> ROOT:made[VERB]
Classifier Explanation:
Random Forest with 12 trees, of which 12 trees voted for the current outcome
Top 1 decision tree justification(s):
[
[
  [ child1.cpos = VERB ],
  [ self.cpos = nexus ],
  [ child.cpos <> NOUN ],
  [ child.keyword <> {have, are, is, what, must, do, has, did, can, on, me, from, were, let} ],
  [ child.suffix <> {y, ing, tion, al, ion, ive} ],
  [ child1.alabel <> DEP ],
  [ child1.keyword <> {down, in, would, own, had, to, most, was, there, been, should, with, could, into, does, when, of, and, the} ],
  [ child1.suffix <> {est, s, ed, ic, ment, er} ],
  [ child3.alabel <> DEP ],
  [ children.card <> 0 ],
  [ parent.keyword <> of ],
  [ parent2.alabel <> PUNCT ]
] ]
```

Formatting output in above form for easier weirdness analysis is implemented outside of the `JustifyingWrapperClassifier` itself because the assumptions we make here might be specific to these features.

### CODE REVIEW

**Comment by mhrmm** [comment]
Hey Sumithra, I'm seeing output like the following (where there are empty
explanations as well as ones that say "12 trees, of which 2 trees voted for
the current outcome" -- which shouldn't be possible in a binary classifying
random forest). Could there be a bug?

Bad families, classified as good:
  Where[ADV] -> ADVMOD:became[VERB]
    (should be: Where[ADV] -> ADVMOD:was[VERB])
Classifier Explanation:

  was[VERB] -> AUXPASS:became[VERB]
    (should be: was[VERB] -> NSUBJ:Nixon[NOUN])
Classifier Explanation:

  nexus[nexus] -> ROOT:became[VERB]
    (should be: nexus[nexus] -> ROOT:was[VERB])
Classifier Explanation:

  became[VERB] -> NSUBJPASS:Nixon[NOUN] DOBJ:president[NOUN]
    (should be: became[VERB] -> ADVCL:was[VERB] NSUBJ:Ford[NOUN]
XCOMP:president[NOUN])
Classifier Explanation:
Random Forest with 12 trees, of which 2 trees voted for the current outcome
Top 1 decision tree justification(s):
[
[
  [ child2.cpos = NOUN ],
  [ parent.cpos = . ],
  [ self.cpos = VERB ],
  [ child.cpos <> {., VERB} ],
  [ child1.alabel <> {VMOD, NSUBJ, AUXPASS, DEP} ],
  [ child1.cpos <> VERB ],
  [ child1.direction <> R ],
  [ child2.alabel <> NSUBJ ],
  [ child2.suffix <> ed ],
  [ child3.cpos <> {VERB, NOUN} ],
  [ children.card <> 0 ],
  [ parent.suffix <> es ],
  [ parent2.alabel <> AUXPASS ],
  [ parent2.suffix <> y ],
  [ parent3.cpos <> . ],
  [ self.suffix <> ed ]
] ]

**Comment by sbhaktha** [comment]
I noticed the same and just fixed a subtle bug that was causing that.
Commit coming up.

**Comment by sbhaktha** [comment]
@mhrmm : issue fixed. Can you give it a go?

**Comment by sbhaktha** [comment]
Just updated the logging to include an output of the gold parse families for reference.  Output now looks like:

```
Who was made the first honorary citizen of the U.S. ?
Gold Families:
  was[VERB] -> AUXPASS:made[VERB]
  citizen[NOUN] -> 
  the[DET] -> DET:citizen[NOUN]
  honorary[ADJ] -> AMOD:citizen[NOUN]
  made[VERB] -> NSUBJPASS:Who[PRON] DOBJ:citizen[NOUN]
  of[ADP] -> PREP:citizen[NOUN] POBJ:U.S.[NOUN]
  Who[PRON] -> 
  U.S.[NOUN] -> 
  the[DET] -> DET:U.S.[NOUN]
  first[ADJ] -> AMOD:citizen[NOUN]
  nexus[nexus] -> ROOT:made[VERB]
  ?[.] -> PUNCT:made[VERB]

Good families, classified as weird:
  nexus[nexus] -> ROOT:made[VERB]
Classifier Explanation: 
Random Forest with 12 trees, of which 12 trees voted for the current outcome
Top 1 decision tree justification(s):
[ 
[
  [ child1.cpos = VERB ],
  [ self.cpos = nexus ],
  [ child.cpos <> NOUN ],
  [ child.keyword <> {have, are, is, what, must, do, has, did, can, on, me, from, were, let} ],
  [ child.suffix <> {y, ing, tion, al, ion, ive} ],
  [ child1.alabel <> DEP ],
  [ child1.keyword <> {down, in, would, own, had, to, most, was, there, been, should, with, could, into, does, when, of, and, the} ],
  [ child1.suffix <> {est, s, ed, ic, ment, er} ],
  [ child3.alabel <> DEP ],
  [ children.card <> 0 ],
  [ parent.keyword <> of ],
  [ parent2.alabel <> PUNCT ]
] ]
```

**Pull request merged**
